/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.eolwral.osmonitor;

public final class R {
    public static final class anim {
        public static final int statusicon=0x7f040000;
    }
    public static final class array {
        public static final int behavior_list_sort=0x7f060002;
        public static final int behaviorvalues_list_sort=0x7f060003;
        public static final int dmesg_level_list=0x7f060005;
        public static final int dmesg_level_value=0x7f060006;
        public static final int entries_list_sort=0x7f060000;
        public static final int entryvalues_list_sort=0x7f060001;
        public static final int logcat_level_list=0x7f060007;
        public static final int logcat_level_value=0x7f060008;
        /**  		<item>Events</item> 
 		<item>Events</item> 
         */
        public static final int logcat_source_list=0x7f060009;
        /**  		<item>2</item>  
 		<item>2</item>  
         */
        public static final int logcat_source_value=0x7f06000a;
        public static final int logtype_list_sort=0x7f060004;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int networklist_color=0x7f070002;
        public static final int networklist_text=0x7f070003;
        public static final int processlist_color=0x7f070000;
        public static final int processlist_text=0x7f070001;
    }
    public static final class drawable {
        public static final int appicon=0x7f020000;
        public static final int battery=0x7f020001;
        public static final int connection=0x7f020002;
        public static final int cpu=0x7f020003;
        public static final int debug=0x7f020004;
        public static final int detailclose=0x7f020005;
        public static final int detailshow=0x7f020006;
        public static final int disk=0x7f020007;
        public static final int load0=0x7f020008;
        public static final int load100=0x7f020009;
        public static final int load20=0x7f02000a;
        public static final int load40=0x7f02000b;
        public static final int load60=0x7f02000c;
        public static final int load80=0x7f02000d;
        public static final int misc=0x7f02000e;
        public static final int monitor=0x7f02000f;
        public static final int network=0x7f020010;
        public static final int point=0x7f020011;
        public static final int process=0x7f020012;
    }
    public static final class id {
        public static final int CPUImageView=0x7f09000c;
        public static final int CPUUsage=0x7f09000e;
        public static final int CPUUsageText=0x7f09000d;
        public static final int Freeze=0x7f090013;
        public static final int MemFreeText=0x7f090011;
        public static final int MemTotalText=0x7f090010;
        public static final int MultiKill=0x7f090015;
        public static final int MultiSelect=0x7f090014;
        public static final int MultiSelectView=0x7f090012;
        public static final int OrderType=0x7f09000f;
        public static final int RunProcessText=0x7f09000b;
        public static final int debugempty=0x7f090003;
        public static final int debuglist=0x7f090002;
        public static final int debugmsgcounts=0x7f090001;
        public static final int debugmsgtext=0x7f090000;
        public static final int diskImage=0x7f090007;
        public static final int diskText=0x7f090008;
        public static final int empty=0x7f09000a;
        public static final int interfacelist=0x7f090004;
        public static final int networklist=0x7f090009;
        public static final int powerImage=0x7f090005;
        public static final int powerText=0x7f090006;
    }
    public static final class layout {
        public static final int debuglayout=0x7f030000;
        public static final int interfacelayout=0x7f030001;
        public static final int mainlayout=0x7f030002;
        public static final int misclayout=0x7f030003;
        public static final int networklayout=0x7f030004;
        public static final int processlayout=0x7f030005;
    }
    public static final class string {
        public static final int about_text=0x7f080063;
        public static final int aboutbtn_text=0x7f080064;
        public static final int aboutoption_text=0x7f08005c;
        public static final int acpower_text=0x7f08002e;
        public static final int app_name=0x7f080000;
        public static final int app_title=0x7f080001;
        public static final int autostart_text=0x7f080050;
        public static final int autostartsum_text=0x7f080051;
        public static final int bar_title=0x7f080002;
        public static final int batteryjni_text=0x7f080027;
        public static final int batteryjnisum_text=0x7f080028;
        public static final int btncancel_title=0x7f08005b;
        public static final int btnok_title=0x7f08005a;
        public static final int capacity_text=0x7f08002b;
        public static final int choicelogtype_text=0x7f080041;
        public static final int choicelogtypesum_text=0x7f080042;
        public static final int clicktitlesum_text=0x7f080018;
        public static final int connection_tab=0x7f080006;
        public static final int cpu_text=0x7f08000a;
        public static final int cpuusage_text=0x7f08004e;
        public static final int cpuusagesum_text=0x7f08004f;
        public static final int debug_tab=0x7f080008;
        public static final int diskavailable_text=0x7f080034;
        public static final int disktotal_text=0x7f080032;
        public static final int diskused_text=0x7f080033;
        public static final int dmesgfilter_text=0x7f080043;
        public static final int exportdone_title=0x7f080059;
        public static final int exportexist_title=0x7f080058;
        public static final int exportfile_title=0x7f080057;
        public static final int filterenable_text=0x7f080046;
        public static final int filterlevel_text=0x7f080049;
        public static final int filterpid_text=0x7f080048;
        public static final int filterstr_text=0x7f080047;
        public static final int forceexit_text=0x7f08005d;
        public static final int freeze_text=0x7f080062;
        public static final int health_text=0x7f080029;
        public static final int hideappbar_text=0x7f080052;
        public static final int hideappbarsum_text=0x7f080053;
        public static final int hidemultiselect_text=0x7f080054;
        public static final int hidemultiselectsum_text=0x7f080055;
        public static final int interface_text=0x7f08001f;
        public static final int ip6to4_title=0x7f080037;
        public static final int ip6to4sum_title=0x7f080038;
        public static final int ip_text=0x7f080020;
        public static final int killdialog_text=0x7f08003e;
        public static final int killdialog_title=0x7f08003d;
        public static final int load_text=0x7f08000f;
        public static final int loading_text=0x7f080012;
        public static final int localremote_text=0x7f080026;
        public static final int logcatfilter_text=0x7f080044;
        public static final int logcatsource_text=0x7f080045;
        public static final int logexport_title=0x7f080056;
        public static final int longclicktitle_text=0x7f080016;
        public static final int mac_text=0x7f080021;
        public static final int mem_text=0x7f080010;
        public static final int memoryfree_text=0x7f08000c;
        public static final int memorytotal_text=0x7f08000b;
        public static final int messagecount_text=0x7f08005e;
        public static final int misc_tab=0x7f080007;
        public static final int multikill_text=0x7f080060;
        public static final int multireset_text=0x7f080061;
        public static final int multiselect_text=0x7f08005f;
        public static final int name_text=0x7f08000e;
        public static final int network_tab=0x7f080005;
        public static final int notify_text=0x7f080003;
        public static final int offline_text=0x7f080031;
        public static final int online_text=0x7f080030;
        public static final int options_text=0x7f080013;
        public static final int pid_text=0x7f08000d;
        public static final int process_tab=0x7f080004;
        public static final int process_text=0x7f080009;
        public static final int protocol_text=0x7f080025;
        public static final int rdns_title=0x7f080039;
        public static final int rdnssum_title=0x7f08003a;
        public static final int rooted_text=0x7f08001d;
        public static final int rootedsum_text=0x7f08001e;
        public static final int rx_text=0x7f080022;
        public static final int shortclicktitle_text=0x7f080017;
        public static final int showiconbar_title=0x7f08004c;
        public static final int showiconbarsum_title=0x7f08004d;
        public static final int showsystem_text=0x7f08001b;
        public static final int showsystemsum_text=0x7f08001c;
        public static final int sortbytitle_text=0x7f080014;
        public static final int sortbytitlesum_text=0x7f080015;
        public static final int sortway_text=0x7f080019;
        public static final int sortwaysum_text=0x7f08001a;
        public static final int status_text=0x7f080024;
        public static final int switchdialog_text=0x7f08003f;
        public static final int technology_text=0x7f08002a;
        public static final int temperature_text=0x7f08002d;
        public static final int thread_text=0x7f080011;
        public static final int tx_text=0x7f080023;
        public static final int updatetime_title=0x7f08004a;
        public static final int updatetimesum_title=0x7f08004b;
        public static final int usbpower_text=0x7f08002f;
        public static final int voltage_text=0x7f08002c;
        public static final int waitdialog_text=0x7f08003c;
        public static final int waitdialog_title=0x7f08003b;
        public static final int watchlog_text=0x7f080040;
        public static final int whoisdialog_title=0x7f080035;
        public static final int whoisdialogsum_title=0x7f080036;
    }
    public static final class xml {
        public static final int preferences=0x7f050000;
    }
}
